# -*- mode: ruby -*-
# # vi: set ft=ruby :
Vagrant.configure(2) do |config|
    (1..1).each do |i|
      config.vm.define "haproxy#{i}" do |s|
        #s.ssh.forward_agent = true
        s.vm.box = "generic/rocky8"
        s.vm.box_version = "3.6.12"
        s.vm.hostname = "haproxy#{i}"
        s.vm.network "public_network", ip: "192.168.1.17#{i+6}", auto_config: true, bridge: "en0"
        ssh_pub_key = File.readlines("./ssh-key.pub").first.strip
        s.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
        s.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
        s.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
        s.vm.provision 'shell', inline: "yum install python3 net-tools -y"
        s.vm.provision "shell",
          run: "always",
          inline: "route add default gw 192.168.1.1"
        # delete default gw on eth0
        s.vm.provision "shell",
          run: "always",
          inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"
        s.vm.provider "parallels" do |v|
          v.name = "haproxy#{i}"
          v.memory = 512
        end
      end
    end
  end
  Vagrant.configure(2) do |config|
    (1..1).each do |i|
      config.vm.define "master#{i}" do |s|
        #s.ssh.forward_agent = true
        s.vm.box = "generic/rocky8"
        s.vm.box_version = "3.6.12"
        s.vm.hostname = "master#{i}"
        s.vm.network "public_network", ip: "192.168.1.18#{i}", auto_config: true, bridge: "en0"
        ssh_pub_key = File.readlines("./ssh-key.pub").first.strip
        s.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
        s.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
        s.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
        s.vm.provision 'shell', inline: "yum install python3 net-tools -y"
        s.vm.provision "shell",
          run: "always",
          inline: "route add default gw 192.168.1.1"
        # delete default gw on eth0
        s.vm.provision "shell",
          run: "always",
          inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"
        s.vm.provider "parallels" do |v|
          v.name = "master#{i}"
          v.memory = 4096
        end
      end
    end
  end
  Vagrant.configure(2) do |config|
    (1..3).each do |i|
      config.vm.define "worker#{i}" do |s|
        #s.ssh.forward_agent = true
        s.vm.box = "generic/rocky8"
        s.vm.box_version = "3.6.12"
        s.vm.hostname = "worker#{i}"
        s.vm.network "public_network", ip: "192.168.1.18#{i+3}", auto_config: true, bridge: "en0"
        ssh_pub_key = File.readlines("./ssh-key.pub").first.strip
        s.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
        s.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
        s.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
        s.vm.provision 'shell', inline: "yum install python3 net-tools -y"
        s.vm.provision "shell",
          run: "always",
          inline: "route add default gw 192.168.1.1"
        # delete default gw on eth0
        s.vm.provision "shell",
          run: "always",
          inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"
        s.vm.provider "parallels" do |v|
          v.name = "worker#{i}"
          v.memory = 5120
          v.customize ["set", :id, "--device-add", "hdd", "--size", "50G", "--iface", "sata"]
        end
      end
    end
  end